<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CSharpAnalyzer\Templates\TestMethodTemplate.txt" />
    <None Remove="CSharpAnalyzer\Templates\UnitTestTemplate.txt" />
    <None Remove="TypeScriptAnalyzer\Templates\SpecTemplate.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CSharpAnalyzer\Templates\TestMethodTemplate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="CSharpAnalyzer\Templates\UnitTestTemplate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="TypeScriptAnalyzer\Templates\SpecTemplate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="TypeScriptAnalyzer\Templates\TestMethodTemplate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.12.0" />
  </ItemGroup>

</Project>
